version: "3.8"

services:

  backend:
    build: ./backend
    container_name: login-backend
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=demo
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: login-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  mysql:
    image: mysql:8
    container_name: login-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
